import sys

Import('env')

files = [
    "exporter.cpp",
]

inc = ['fcollada']

defines = ['UNICODE']

if 'linux' in sys.platform:
    defines.append("LINUX")

env.Program("exporter", files, 
    LIBS = ['fcollada', 'dl'], 
    CPPDEFINES = defines,
    LIBPATH = ['fcollada'],
    CPPPATH = [
        'fcollada', 
        'fcollada/LibXML/include',
        'fcollada/FCDocument',
        ]) 

