import sys

Import('env')

files = [
    "exporter.cpp",
    "exporter.h",
    "main.cpp",
    "asset.h",
    "asset.cpp",
    "jumpgate_asset.h",
    "jumpgate_asset.cpp",
]

inc = ['fcollada']

defines = ['UNICODE', 'JUMPGATE']

if 'linux' in sys.platform:
    defines.append("LINUX")

env.Program("exporter", files, 
    LIBS = ['fcollada', 'dl'], 
    CPPDEFINES = defines,
    LIBPATH = ['fcollada'],
    CPPPATH = [
        'fcollada', 
        'fcollada/LibXML/include',
        'fcollada/FCDocument',
        'fcollada/FUtils',
        ]) 

